# Generated by Django 6.1 on 2026-09-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vehiculo', 'Vehículo'), ('apartamento', 'Apartamento'), ('casa', 'Casa'), ('motocicleta', 'Motocicleta'), ('lote', 'Lote'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('arrendado', 'Arrendado')], default='disponible', max_length=20)),
            ],
        ),
    ]
