# Generated by Django 6.1 on 2026-09-04 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_inmueble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='negocios.persona')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='negocios.inmueble')),
            ],
        ),
    ]
