# Generated by Django 6.1 on 2026-09-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financiamiento', to='negocios.venta')),
            ],
        ),
    ]
