# Generated by Django 6.1 on 2026-09-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_financiamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_pagada', 'Parcialmente Pagada'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='negocios.financiamiento')),
            ],
            options={
                'unique_together': {('financiamiento', 'numero_cuota')},
            },
        ),
    ]
