# Generated by Django 6.1 on 2026-09-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canon_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dia_pago', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_arrendados', to='negocios.persona')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='negocios.inmueble')),
            ],
        ),
    ]
