# Generated by Django 6.1 on 2026-09-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligacionArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_obligacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_pagada', 'Parcialmente Pagada'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='negocios.arriendo')),
            ],
            options={
                'unique_together': {('arriendo', 'periodo')},
            },
        ),
    ]
