# Generated by Django 6.1 on 2026-09-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_obligacionarriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField()),
                ('valor_honorario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcialmente_pagada', 'Parcialmente Pagada'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='honorarios', to='negocios.persona')),
            ],
        ),
    ]
