# Generated by Django 6.1 on 2026-09-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_movimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Honorarios',
            new_name='Honorario',
        ),
    ]
