# Generated by Django 6.1 on 2026-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_rename_honorarios_honorario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['activa', 'pagada'])), fields=('inmueble',), name='una_venta_activa_por_inmueble'),
        ),
    ]
