# Generated by Django 6.1 on 2026-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_venta_una_venta_activa_por_inmueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(unique=True),
        ),
    ]
