# Generated by Django 6.1 on 2026-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0012_alter_inmueble_descripcion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='arriendo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('inmueble',), name='un_arriendo_activo_por_inmueble'),
        ),
    ]
