# Generated by Django 6.1 on 2026-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0013_arriendo_un_arriendo_activo_por_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='honorario',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obligacionarriendo',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
